/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompleteRegistrationRouteImport } from './routes/complete-registration'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppOwnerRouteImport } from './routes/_app.owner'
import { Route as AppBaristaRouteImport } from './routes/_app.barista'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppOwnerIndexRouteImport } from './routes/_app.owner.index'
import { Route as AppBaristaIndexRouteImport } from './routes/_app.barista.index'
import { Route as AppOwnerCustomersRouteImport } from './routes/_app.owner.customers'
import { Route as AppOwnerBaristasRouteImport } from './routes/_app.owner.baristas'
import { Route as AppOwnerAnalyticsRouteImport } from './routes/_app.owner.analytics'
import { Route as AppBaristaRedeemRouteImport } from './routes/_app.barista.redeem'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRegistrationRoute = CompleteRegistrationRouteImport.update({
  id: '/complete-registration',
  path: '/complete-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOwnerRoute = AppOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AppRoute,
} as any)
const AppBaristaRoute = AppBaristaRouteImport.update({
  id: '/barista',
  path: '/barista',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerIndexRoute = AppOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOwnerRoute,
} as any)
const AppBaristaIndexRoute = AppBaristaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBaristaRoute,
} as any)
const AppOwnerCustomersRoute = AppOwnerCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppOwnerRoute,
} as any)
const AppOwnerBaristasRoute = AppOwnerBaristasRouteImport.update({
  id: '/baristas',
  path: '/baristas',
  getParentRoute: () => AppOwnerRoute,
} as any)
const AppOwnerAnalyticsRoute = AppOwnerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppOwnerRoute,
} as any)
const AppBaristaRedeemRoute = AppBaristaRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => AppBaristaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-registration': typeof CompleteRegistrationRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/barista': typeof AppBaristaRouteWithChildren
  '/owner': typeof AppOwnerRouteWithChildren
  '/barista/redeem': typeof AppBaristaRedeemRoute
  '/owner/analytics': typeof AppOwnerAnalyticsRoute
  '/owner/baristas': typeof AppOwnerBaristasRoute
  '/owner/customers': typeof AppOwnerCustomersRoute
  '/barista/': typeof AppBaristaIndexRoute
  '/owner/': typeof AppOwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-registration': typeof CompleteRegistrationRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/barista/redeem': typeof AppBaristaRedeemRoute
  '/owner/analytics': typeof AppOwnerAnalyticsRoute
  '/owner/baristas': typeof AppOwnerBaristasRoute
  '/owner/customers': typeof AppOwnerCustomersRoute
  '/barista': typeof AppBaristaIndexRoute
  '/owner': typeof AppOwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/complete-registration': typeof CompleteRegistrationRoute
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/barista': typeof AppBaristaRouteWithChildren
  '/_app/owner': typeof AppOwnerRouteWithChildren
  '/_app/barista/redeem': typeof AppBaristaRedeemRoute
  '/_app/owner/analytics': typeof AppOwnerAnalyticsRoute
  '/_app/owner/baristas': typeof AppOwnerBaristasRoute
  '/_app/owner/customers': typeof AppOwnerCustomersRoute
  '/_app/barista/': typeof AppBaristaIndexRoute
  '/_app/owner/': typeof AppOwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-registration'
    | '/login'
    | '/admin'
    | '/barista'
    | '/owner'
    | '/barista/redeem'
    | '/owner/analytics'
    | '/owner/baristas'
    | '/owner/customers'
    | '/barista/'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-registration'
    | '/login'
    | '/admin'
    | '/barista/redeem'
    | '/owner/analytics'
    | '/owner/baristas'
    | '/owner/customers'
    | '/barista'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/complete-registration'
    | '/login'
    | '/_app/admin'
    | '/_app/barista'
    | '/_app/owner'
    | '/_app/barista/redeem'
    | '/_app/owner/analytics'
    | '/_app/owner/baristas'
    | '/_app/owner/customers'
    | '/_app/barista/'
    | '/_app/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CompleteRegistrationRoute: typeof CompleteRegistrationRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-registration': {
      id: '/complete-registration'
      path: '/complete-registration'
      fullPath: '/complete-registration'
      preLoaderRoute: typeof CompleteRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/owner': {
      id: '/_app/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AppOwnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/barista': {
      id: '/_app/barista'
      path: '/barista'
      fullPath: '/barista'
      preLoaderRoute: typeof AppBaristaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner/': {
      id: '/_app/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AppOwnerIndexRouteImport
      parentRoute: typeof AppOwnerRoute
    }
    '/_app/barista/': {
      id: '/_app/barista/'
      path: '/'
      fullPath: '/barista/'
      preLoaderRoute: typeof AppBaristaIndexRouteImport
      parentRoute: typeof AppBaristaRoute
    }
    '/_app/owner/customers': {
      id: '/_app/owner/customers'
      path: '/customers'
      fullPath: '/owner/customers'
      preLoaderRoute: typeof AppOwnerCustomersRouteImport
      parentRoute: typeof AppOwnerRoute
    }
    '/_app/owner/baristas': {
      id: '/_app/owner/baristas'
      path: '/baristas'
      fullPath: '/owner/baristas'
      preLoaderRoute: typeof AppOwnerBaristasRouteImport
      parentRoute: typeof AppOwnerRoute
    }
    '/_app/owner/analytics': {
      id: '/_app/owner/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof AppOwnerAnalyticsRouteImport
      parentRoute: typeof AppOwnerRoute
    }
    '/_app/barista/redeem': {
      id: '/_app/barista/redeem'
      path: '/redeem'
      fullPath: '/barista/redeem'
      preLoaderRoute: typeof AppBaristaRedeemRouteImport
      parentRoute: typeof AppBaristaRoute
    }
  }
}

interface AppBaristaRouteChildren {
  AppBaristaRedeemRoute: typeof AppBaristaRedeemRoute
  AppBaristaIndexRoute: typeof AppBaristaIndexRoute
}

const AppBaristaRouteChildren: AppBaristaRouteChildren = {
  AppBaristaRedeemRoute: AppBaristaRedeemRoute,
  AppBaristaIndexRoute: AppBaristaIndexRoute,
}

const AppBaristaRouteWithChildren = AppBaristaRoute._addFileChildren(
  AppBaristaRouteChildren,
)

interface AppOwnerRouteChildren {
  AppOwnerAnalyticsRoute: typeof AppOwnerAnalyticsRoute
  AppOwnerBaristasRoute: typeof AppOwnerBaristasRoute
  AppOwnerCustomersRoute: typeof AppOwnerCustomersRoute
  AppOwnerIndexRoute: typeof AppOwnerIndexRoute
}

const AppOwnerRouteChildren: AppOwnerRouteChildren = {
  AppOwnerAnalyticsRoute: AppOwnerAnalyticsRoute,
  AppOwnerBaristasRoute: AppOwnerBaristasRoute,
  AppOwnerCustomersRoute: AppOwnerCustomersRoute,
  AppOwnerIndexRoute: AppOwnerIndexRoute,
}

const AppOwnerRouteWithChildren = AppOwnerRoute._addFileChildren(
  AppOwnerRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBaristaRoute: typeof AppBaristaRouteWithChildren
  AppOwnerRoute: typeof AppOwnerRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBaristaRoute: AppBaristaRouteWithChildren,
  AppOwnerRoute: AppOwnerRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CompleteRegistrationRoute: CompleteRegistrationRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
